### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException on Android

### ISSUE THREAD

**Issue by goheroes** [sendbird/react-native-scrollview-enhancer#3]
sendbird ui-kit을 이용해 그룹챗을 적용시켰습니다.

그룹채널 입출 과정이나 대기상태에서 랜덤하게 발생해서 정확한 구현과정은 찾지 못했습니다.
오류코드 살펴본 후 해당 라이브러리에서 발생하는 것 같아 이곳에 제보합니다.

* 발생환경
"react-native": "0.70.8",
"@sendbird/react-native-scrollview-enhancer": "^0.2.0",
OS 버전: android12
모델:V50S ThinQ
OS 버전: android13
모델:Galaxy S21 5G
ios에서는 에러 발생하지 않았습니다.

```
Fatal Exception: java.lang.NullPointerException:
       at com.scrollviewenhancer.MaintainVisibleScrollPositionHelper.updateScrollPosition(MaintainVisibleScrollPositionHelper.kt:110)
       at com.scrollviewenhancer.MaintainVisibleScrollPositionHelper.onLayoutUpdated(MaintainVisibleScrollPositionHelper.kt:168)
       at com.facebook.react.uimanager.UIViewOperationQueue$LayoutUpdateFinishedOperation.execute(UIViewOperationQueue.java:566)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:847)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by bang9** [comment]
안녕하세요 @sendbird/react-native-scrollview-enhancer 버전을 [0.2.1](https://github.com/sendbird/react-native-scrollview-enhancer/releases/tag/v0.2.1) 으로 업데이트를 해보시겠어요?
